### ISSUE TITLE
snippet-bot complaining about region tag prefix

### ISSUE THREAD

**Issue by changsongd** [googleapis/python-optimization#14] opened 2022-04-05 22:38 UTC
I'm creating code samples for the optimization ai GA. 

snippet-bot is unhappy about the region tags in both of my PR: https://github.com/googleapis/python-optimization/pull/12 and  https://github.com/googleapis/python-optimization/pull/13 

The error message is this:
```
Some region tags do not have appropriate prefix
There is a possible violation for not having product prefix.
samples/snippets/sync_api.py:15, tag cloudoptimization_sync_api
```

The region tags I'm using are `cloudoptimization_sync_api` and `cloudoptimization_get_operation`. Both are created more than 8 hrs ago.

The region tag prefix seems already registered here: https://devrel.corp.google.com/admin/products/463?t=snippets

Could someone help check why the snippet-bot is unhappy?

**Comment by parthea** [comment] 2022-04-08 11:12
Closing as a duplicate of https://github.com/googleapis/repo-automation-bots/issues/3400

**Closed by parthea** 2022-04-08 11:12 UTC
Labels: type: question, api: cloudoptimization
